server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/widgetstoredb
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: DEBUG

user:
  layout:
    storage:
      # Storage path for user layout files
      # Default: data/users (relative to project root)
      # Production: /data/users (absolute path)
      path: data/users
